modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Addon for FTB Quests that adds a translate button to the quest view panel.
Translates quest title, subtitle and description on-the-fly using free translation APIs.
Translation is temporary - closing the quest panel restores original text.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ftbquests"
    type="required"
    reason="This is an addon for FTB Quests"
    versionRange="[2101.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ftblibrary"
    type="required"
    reason="Required by FTB Quests"
    versionRange="[2101.1.0,)"
    ordering="AFTER"
    side="BOTH"
